require 'rake/testtask'
require 'rubygems/package_task'
require 'rake/testtask'

begin
  load 'spec/spec.rake'
rescue LoadError => e
  STDERR.puts "Could not load spec.rake, specs will not be available"
end

def gemspec
  @gemspec ||= begin
    file = File.expand_path("eson-http.gemspec")
    ::Gem::Specification.load(file)
  end
end

desc "Validates the gemspec"
task :gemspec do
  gemspec.validate
end

Gem::PackageTask.new(gemspec) do |pkg|
  pkg.gem_spec = gemspec
end

task :package => :gemspec

Rake::TestTask.new(:test) do |test|
  test.pattern = 'test/**/*_test.rb'
  
  test.verbose = true
end

task :seed do
  require './test/seeds/seeds'
end